[package]
name = "Pegasus"
version = "0.1.0"
authors = ["black.dragon74 <nickk.2974@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
